_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 8
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.7
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 200
epochs:
    value: 10
learning_rate:
    value: 0.001
